- name: Ensure plasma metapackage is installed
  become: true
  community.general.pacman:
    name: plasma-meta
    state: present

- name: Install KDE utilities not included in plasma metapackage
  become: true
  community.general.pacman:
    name:
      - ark
      - kgpg
      - kwalletmanager
      - spectacle
      - partitionmanager
    state: present

- name: Ensure sddm is enabled
  become: true
  ansible.builtin.systemd_service:
    name: sddm.service
    enabled: true
    force: true
