user: "almond"
home: "/home/{{ user }}"

# git projects to clone into ~/git
git_projects:
  - name: almondheil.github.io
    url: git@github.com:almondheil/almondheil.github.io.git
  - name: resume
    url: git@github.com:almondheil/resume.git
  - name: ftag
    url: git@github.com:almondheil/ftag.git
  - name: gonote
    url: git@github.com:almondheil/gonote.git

sync_dir: "{{ home }}/sync"
sync_symlinks:
  - src: "{{ sync_dir }}/TODO.md"
    dest: "{{ home }}/TODO.md"
  - src: "{{ sync_dir }}/dot_todo"
    dest: "{{ home }}/.todo"

# what directories should be removed from home, and what should be added?
home_subdir_remove:
  - Desktop
  - Documents
  - Downloads
  - Music
  - Pictures
  - Public
  - Templates
  - Videos
home_subdir_create:
  - download
  - sync
  - truenas-media
  - virtualbox
