---
- name: Force-apply all chezmoi configs
  ansible.builtin.command:
    cmd: chezmoi apply --force # noqa: no-changed-when

- name: Reboot system
  become: true
  ansible.builtin.command:
    cmd: reboot now # noqa: no-changed-when
