---
# https://github.com/kewlfft/ansible-aur
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

# https://github.com/kewlfft/ansible-aur
- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0440
    validate: 'visudo -cf %s'

- ansible.builtin.import_tasks: paru.yml
  when: aur_helper == "paru"

- ansible.builtin.import_tasks: yay.yml
  when: aur_helper == "yay"
