---
- name: Install rustup
  become: true
  community.general.pacman:
    name: rustup
    state: present

- name: Set `aur_builder` rustup version to stable
  become: true
  become_user: aur_builder
  command: rustup default stable

- name: Set running user rustup version to stable
  command: rustup default stable

- name: Install paru through the aur
  kewlfft.aur.aur:
    name: paru
    state: present
    use: makepkg
  become: true 
  become_user: aur_builder
