---
- name: Install virtualbox
  become: true
  community.general.pacman:
    name:
      - virtualbox
      # assuming we're using the `linux` kernel, this is the correct host modules
      - virtualbox-host-modules-arch
    state: present
  notify:
    - Load virtualbox kernel modules

- name: Add user to vboxusers group for VM USB access
  become: true
  ansible.builtin.user:
    name: '{{ user }}'
    groups: vboxusers
    append: true

- name: Install guest additions on host
  become: true
  community.general.pacman:
    name: virtualbox-guest-iso
    state: present

- name: Install personal use only extension pack from AUR
  kewlfft.aur.aur:
    name: virtualbox-ext-oracle
    state: present
