- name: Delete firefox from system repos
  become: true
  community.general.pacman:
    name: firefox
    state: absent

- name: Install firefox from flatpak
  community.general.flatpak:
    name: org.mozilla.firefox
    state: present
