- name: Delete firefox from system repos
  become: true
  community.general.pacman:
    name: firefox
    state: present

- name: Install firefox from flatpak
  flatpak:
    name: org.mozilla.firefox
    state: present
