---
- name: Install wireguard
  become: true
  community.general.pacman:
    name: wireguard-tools
    state: present

- name: Install net-tools for ifconfig
  become: true
  community.general.pacman:
    name: net-tools
    state: present

- name: Enable and start systemd-resolved service
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    enabled: true
    state: started

- name: Install systemd resolvconf
  become: true
  community.general.pacman:
    name: systemd-resolvconf
    state: present
