---
- hosts: laptop
  vars_prompt:
    - name: chezmoi_passphrase
      prompt: Chezmoi encrpyion passphrase
  roles:
    - { role: chezmoi, tags: ['chezmoi'] }
    - { role: flatpak, tags: ['flatpak', 'package'] }
    - { role: pacman-apps, tags: ['pacman', 'package'] }
    - { role: yay, tags: ['yay', 'package'] }
    - { role: gnome-misc, tags: ['gnome-misc', 'gnome']}
    # - { role: gnome-shortcuts, tags: ['gnome-shortcuts', 'gnome']}
    - { role: gnome-touchpad, tags: ['gnome-touchpad', 'gnome']}
    - { role: zsh, tags: ['zsh', 'shell']}
