---
- hosts: laptop
  vars_prompt:
    - name: chezmoi_passphrase
      prompt: Chezmoi encrpyion passphrase
  roles:
    # install yay and flatpak to make sure they are available
    - { role: yay, tags: ['yay', 'package'] }
    - { role: flatpak, tags: ['flatpak', 'package'] }

    # install chezmoi, apply the configuration management changes
    - { role: chezmoi, tags: ['chezmoi'] }

    # do app-specific administration
    - { role: firefox, tags: ['firefox'] }
    - { role: gnome, tags: ['gnome'] }
    - { role: misc-packages, tags: ['misc-packages'] }
    - { role: nextcloud, tags: ['nextcloud'] }
    - { role: zsh, tags: ['zsh', 'shell'] }
