---
- name: Run whole playbook
  hosts: laptop
  vars_prompt:
    - name: chezmoi_passphrase
      prompt: Chezmoi encrpyion passphrase
  roles:
    # install aur and flatpak to make sure they are available for future roles
    - { role: aur, tags: ['aur'] }
    - { role: flatpak, tags: ['flatpak'] }
    - { role: rust, tags: ['rust', 'cargo'] }

    # install chezmoi and get it started
    # (user will still need to apply changes, except for ~/.ssh)
    - { role: chezmoi, tags: ['chezmoi'] }

    # everything else
    - { role: airvpn, tags: ['airvpn'] }
    - { role: art_apps, tags: ['art_apps'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: caps2esc, tags: ['caps2esc'] }
    - { role: chat_apps, tags: ['chat_apps'] }
    - { role: editors, tags: ['editors'] }
    - { role: fingerprint, tags: ['fingerprint'] }
    - { role: firefox, tags: ['firefox'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: framework, tags: ['framework'] }
    - { role: fwupd, tags: ['fwupd'] }
    - { role: git, tags: ['git'] }
    - { role: go, tags: ['go'] }
    - { role: home, tags: ['home'] }
    - { role: kde, tags: ['kde'] }
    - { role: latex, tags: ['latex'] }
    - { role: mail, tags: ['mail'] }
    - { role: snapper, tags: ['snapper'] }
    - { role: steam, tags: ['steam'] }
    - { role: syncthing, tags: ['syncthing'] }
    - { role: tailscale, tags: ['tailscale'] }
    - { role: tools, tags: ['tools'] }
    - { role: udev, tags: ['udev'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: zotero, tags: ['zotero'] }
    - { role: zsh, tags: ['zsh'] }
