---
- hosts: laptop
  vars_prompt:
    - name: chezmoi_passphrase
      prompt: Chezmoi encrpyion passphrase
  roles:
    # install yay and flatpak to make sure they are available
    - { role: flatpak, tags: ['flatpak', 'package'] }
    - { role: paru, tags: ['paru', 'aur', 'package'] }

    # install chezmoi, apply the configuration management changes
    - { role: chezmoi, tags: ['chezmoi'] }

    # do app-specific administration
    - { role: airvpn, tags: ['airvpn', 'vpn'] }
    - { role: aseprite, tags: ['aseprite'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: fingerprint, tags: ['fingerprint'] }
    - { role: firefox, tags: ['firefox'] }
    - { role: framework, tags: ['framework'] }
    - { role: gnome, tags: ['gnome'] }
    - { role: lvim, tags: ['lvim'] }
    - { role: mail, tags: ['mail'] }
    - { role: misc-packages, tags: ['misc-packages'] }
    - { role: nextcloud, tags: ['nextcloud'] }
    - { role: opam, tags: ['opam', 'ocaml'] }
    - { role: snapper, tags: ['snapper', 'btrfs'] }
    - { role: steam, tags: ['steam'] }
    - { role: superdrive, tags: ['superdrive', 'udev'] }
    - { role: tailscale, tags: ['tailscale', 'vpn'] }
    - { role: zsh, tags: ['zsh', 'shell'] }
