---
- hosts: laptop
  vars_prompt:
    - name: chezmoi_passphrase
      prompt: Chezmoi encrpyion passphrase
  roles:
    - { role: chezmoi, tags: ['chezmoi'] }
    - { role: flatpak, tags: ['flatpak', 'package'] }
    - { role: gnome, tags: ['gnome']}
    - { role: pacman, tags: ['pacman', 'package'] }
    - { role: yay, tags: ['yay', 'package'] }
    - { role: zsh, tags: ['zsh', 'shell']}
