---
- hosts: laptop
  vars_prompt:
    - name: chezmoi_passphrase
      prompt: Chezmoi encrpyion passphrase
  roles:
    # install aur and flatpak to make sure they are available
    - { role: aur, tags: ['aur', 'package'] }
    - { role: flatpak, tags: ['flatpak', 'package'] }

    # install chezmoi, apply the configuration management changes
    - { role: chezmoi, tags: ['chezmoi'] }

    # do app-specific administration
    - { role: airvpn, tags: ['airvpn', 'vpn'] }
    - { role: art-apps, tags: ['art-apps'] }
    - { role: bluetooth, tags: ['bluetooth'] }
    - { role: caps2esc, tags: ['caps2esc'] }
    - { role: chat-apps, tags: ['chat-apps'] }
    - { role: editors, tags: ['editors'] }
    - { role: fingerprint, tags: ['fingerprint'] }
    - { role: firefox, tags: ['firefox'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: framework, tags: ['framework'] }
    - { role: gnome, tags: ['gnome'] }
    - { role: latex, tags: ['latex'] }
    - { role: mail, tags: ['mail'] }
    - { role: nextcloud, tags: ['nextcloud'] }
    - { role: opam, tags: ['opam', 'ocaml'] }
    - { role: snapper, tags: ['snapper', 'btrfs'] }
    - { role: steam, tags: ['steam'] }
    - { role: superdrive, tags: ['superdrive', 'udev'] }
    - { role: tailscale, tags: ['tailscale', 'vpn'] }
    - { role: tools, tags: ['tools'] }
    - { role: zotero, tags: ['zotero'] }
    - { role: zsh, tags: ['zsh'] }
