---
- name: Setup laptop
  hosts: localhost
  vars_prompt:
    - prompt: Chezmoi encrpyion passphrase
      name: chezmoi_passphrase
  roles:
    # first phase: package installs and init stuff
    - { role: 'aur', tags: ['aur'] }
    - { role: 'flatpak', tags: ['flatpak'] }
    - { role: 'packages', tags: ['packages'] }
    - { role: 'directories', tags: ['directories'] }

    # middle phase: no dependencies between roles
    - { role: 'caps2esc', tags: ['caps2esc'] }
    - { role: 'chezmoi', tags: ['chezmoi'] }
    - { role: 'custom_tools', tags: ['custom_tools'] }
    - { role: 'figlet', tags: ['figlet'] }
    - { role: 'fingerprint', tags: ['fingerprint'] }
    - { role: 'fonts', tags: ['fonts'] }
    - { role: 'git_projects', tags: ['git_projects'] }
    - { role: 'steam', tags: ['steam'] }
    - { role: 'udev', tags: ['udev'] }

    # final phase: enable services, including newly-installed ones
    # if -t fresh_install is specified we will reboot etc, otherwise skip that.
    - { role: 'services', tags: ['services'] }
    - { role: 'fresh_install', tags: ['never', 'fresh_install'] }
