---
- name: Package and dir setup
  hosts: localhost
  roles:
    - { role: 'aur', tags: ['aur'] }
    - { role: 'flatpak', tags: ['flatpak'] }
    - { role: 'packages', tags: ['packages'] }
    - { role: 'directories', tags: ['directories'] }

- name: Per-program configuration
  hosts: localhost
  vars_prompt:
    - prompt: Chezmoi encrpyion passphrase
      name: chezmoi_passphrase
  roles:
    - { role: 'caps2esc', tags: ['caps2esc'] }
    - { role: 'chezmoi', tags: ['chezmoi'] }
    - { role: 'custom_tools', tags: ['custom_tools'] }
    - { role: 'figlet', tags: ['figlet'] }
    - { role: 'fingerprint', tags: ['fingerprint'] }
    - { role: 'fonts', tags: ['fonts'] }
    - { role: 'git_projects', tags: ['git_projects'] }
    - { role: 'pam', tags: ['pam'] }
    - { role: 'shell', tags: ['shell'] }
    - { role: 'steam', tags: ['steam'] }
    - { role: 'udev', tags: ['udev'] }

- name: Final
  hosts: localhost
  roles:
    - { role: 'services', tags: ['services'] }
    - { role: 'fresh_install', tags: ['never', 'fresh_install'] }
