---
- name: Setup laptop
  hosts: localhost
  vars_prompt:
    - prompt: Chezmoi encrpyion passphrase
      name: chezmoi_passphrase
  roles:
    # prioritize setup that will be needed later
    - { role: 'aur', tags: ['setup', 'packages', 'aur', 'setup_aur'] }
    - { role: 'chezmoi', tags: ['setup', 'chezmoi', 'setup_chezmoi'] }
    - { role: 'flatpak', tags: ['setup', 'packages', 'flatpak', 'setup_flatpak'] }
    - { role: 'git_projects', tags: ['setup', 'git_projects', 'setup_git_projects'] }
    - { role: 'home_dirs', tags: ['setup', 'home_dirs', 'setup_home_dirs'] }

    # for others, order should not matter (unless marked) -- put in alphabetical.
    - { role: 'caps2esc', tags: ['caps2esc'] }
    - { role: 'custom_tools', tags: ['custom_tools', 'tools'] }
    - { role: 'figlet', tags: ['figlet'] }
    - { role: 'framework', tags: ['framework'] }
    - { role: 'packages', tags: ['packages'] }
    - { role: 'udev', tags: ['udev'] }
    - { role: 'fingerprint', tags: ['fingerprint'] }
    - { role: 'steam', tags: ['steam'] }

    # after all other roles have run, I assume config files have been dropped.
    # that makes it the right time to start any services
    - { role: 'services', tags: ['services'] }
