---
- name: Setup laptop
  hosts: localhost
  roles:
    # prioritize setup that will be needed later
    - { role: 'setup/aur', tags: ['setup', 'packages', 'setup/aur'] }
    - { role: 'setup/flatpak', tags: ['setup', 'packages', 'setup/flatpak'] }
    - { role: 'setup/git_projects', tags: ['setup', 'setup/git_projects'] }
    - { role: 'setup/home_dirs', tags: ['setup', 'setup/home_dirs'] }

    # for others, order should not matter (unless marked) -- put in alphabetical.
    - { role: 'figlet', tags: ['figlet'] }
    - { role: 'framework', tags: ['framework'] }
    - { role: 'packages', tags: ['packages'] }
    - { role: 'udev', tags: ['udev'] }
