- name: Install Zotero
  flatpak:
    name: org.zotero.Zotero
    state: present

- name: Override zotero flatpak to allow access to /opt
  command: flatpak --user override --filesystem=/opt:ro org.zotero.Zotero
