# set some overall ansible options
ansible_connection: 'local'
ansible_python_interpreter: 'auto_silent'

# configs for basic user info
user: 'almond'
home: '/home/{{ user }}'
default_shell: '/usr/bin/fish'
