- name: Install interception-tools
  become: true
  community.general.pacman:
    name: interception-tools
    state: present

- name: Install interception-tools caps2esc plugin
  become: true
  community.general.pacman:
    name: interception-caps2esc
    state: present

- name: Start and enable udevmon systemd service
  become: true
  ansible.builtin.service:
    name: udevmon
    state: started
    enabled: true

- name: Drop caps2esc udevmon configuration
  become: true
  ansible.builtin.copy:
    src: caps2esc_udevmon.yaml
    dest: /etc/interception/udevmon.d/caps2esc.yaml
    mode: "0644"
