---
- name: Install bluez
  become: true
  community.general.pacman:
    name: bluez
    state: present

- name: Start bluetooth service
  become: true
  systemd:
    name: bluetooth.service
    state: started
    enabled: true
