---
- name: Enable multilib repo
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  notify:
    - Install vulkan for Intel integrated graphics
    - Install steam
