---
- name: Enable multilib repo
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Update pacman cache (always runs)
  become: true
  community.general.pacman:
    update_cache: true

- name: Install steam with vulkan-intel graphics
  become: true
  ansible.builtin.package:
    name:
      - steam
      - lib32-vulkan-intel
    state: present
