---
- name: Enable multilib repo
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Update pacman cache (always runs)
  become: true
  community.general.pacman:
    update_cache: true

- name: Install steam with vulkan-intel graphics
  become: true
  ansible.builtin.package:
    name:
      - steam
      - lib32-vulkan-intel
    state: present

- name: Drop steam-move-screenshots script
  become: true
  ansible.builtin.template:
    src: 'templates/script/steam-move-screenshots.sh.j2'
    dest: '/usr/bin/steam-move-screenshots.sh'
    mode: '0755'

- name: Drop steam-move-screenshots systemd units
  become: true
  ansible.builtin.template:
    src: 'templates/systemd/steam-move-screenshots.{{ item }}.j2'
    dest: '/usr/lib/systemd/system/steam-move-screenshots.{{ item }}'
    mode: '0644'
  with_items: ['service', 'timer']

- name: Reload systemd to show new units (always runs)
  become: true
  ansible.builtin.systemd_service:
    daemon-reload: true
