# dirs to create owned by your user, with specified mode
home_dirs_mode: '0700'
home_dirs:
  - '{{ ansible_facts["env"]["HOME"] }}/.config/chezmoi'
  - '{{ ansible_facts["env"]["HOME"] }}/.fonts'
  - '{{ ansible_facts["env"]["HOME"] }}/.local/share'
  - '{{ ansible_facts["env"]["HOME"] }}/.ssh'
  - '{{ ansible_facts["env"]["HOME"] }}/download'
  - '{{ ansible_facts["env"]["HOME"] }}/git'
  - '{{ sync_dir }}'

# dirs to create owned by root:root, with specified mode
root_dirs_mode: '0755'
root_dirs:
  - /etc/interception/udevmon.d

# dirs to delete, with no checking or backing up
delete_dirs:
  - '{{ ansible_facts["env"]["HOME"] }}/Desktop'
  - '{{ ansible_facts["env"]["HOME"] }}/Documents'
  - '{{ ansible_facts["env"]["HOME"] }}/Downloads'
  - '{{ ansible_facts["env"]["HOME"] }}/Music'
  - '{{ ansible_facts["env"]["HOME"] }}/Pictures'
  - '{{ ansible_facts["env"]["HOME"] }}/Public'
  - '{{ ansible_facts["env"]["HOME"] }}/Templates'
  - '{{ ansible_facts["env"]["HOME"] }}/Videos'
