sync_dir: '{{ ansible_facts["env"]["HOME"] }}/sync'
sync_symlinks:
  - src: 'dot_todo'
    dest: '{{ ansible_facts["env"]["HOME"] }}/.todo'
  - src: 'vimwiki'
    dest: '{{ ansible_facts["env"]["HOME"] }}/vimwiki'
