---
- name: Install dependencies
  become: true
  community.general.pacman:
    name:
      - git
      - lazygit
      - make
      - neovim
      - nodejs
      - npm
      - python-pip
      - python-pynvim
      - ripgrep
    state: present

- name: Clone from git
  git:
    # clone the master version, and not the 1.4 release version
    # as of 2024-08-11, this fixes https://github.com/LunarVim/LunarVim/issues/4477
    # (should get fixed in 1.5 release)
    repo: https://github.com/LunarVim/LunarVim.git
    dest: /tmp/lunarvim

- name: Run install script
  shell:
    creates: "{{ home }}/.local/bin/lvim"
    cmd: |
      export LV_BRANCH={{ lvim_release | quote }}
      bash /tmp/lunarvim/utils/installer/install.sh -y

- name: Cleanup git repo
  file:
    path: /tmp/lunarvim
    state: absent
