---
- name: Install dependencies
  become: true
  community.general.pacman:
    name:
      - git
      - lazygit
      - make
      - neovim
      - nodejs
      - npm
      - python-pip
      - python-pynvim
      - ripgrep
    state: present

- name: Run install script
  shell:
    creates: "{{ home }}/.local/bin/lvim"
    cmd: |
      LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)
      send 'y' # node dependencies
      send 'n' # python dependency pynvim (already installed, would cause crash by calling pip)
      send 'y' # rust dependencies
      exit 0
