---
- name: Install chezmoi and dependencies
  become: true
  community.general.pacman:
    name:
      - chezmoi
      - git
      - age
    state: present

- name: Initialize chezmoi (github HTTPS)
  ansible.builtin.command:
    cmd: chezmoi init --ssh almondheil
    creates: "{{ home }}/.local/share/chezmoi"
  notify: Set chezmoi remote to SSH

- name: Drop filled-in chezmoi config
  ansible.builtin.copy:
    src: chezmoi.toml
    dest: "{{ home }}/.config/chezmoi/chezmoi.toml"
    mode: '0600'

- name: Decrypt chezmoi age key
  # requires pexpect python package to run
  ansible.builtin.expect:
    command: age -d -o "{{ home }}/.config/chezmoi/key.txt" "{{ home }}/.local/share/chezmoi/key.txt.age"
    responses:
      "Enter passphrase:": "{{ chezmoi_passphrase }}"
    creates: "{{ home }}/.config/chezmoi/key.txt"

- name: Ensure restricted permissions on chezmoi age key
  ansible.builtin.file:
    path: "{{ home }}/.config/chezmoi/key.txt"
    mode: '0600'
