---
- name: Install chezmoi and dependencies
  become: true
  community.general.pacman:
    name:
      - chezmoi
      - git
      - age
    state: present

- name: Initialize chezmoi
  command:
    cmd: chezmoi init --verbose almondheil
    creates: "{{ home }}/.local/share/chezmoi"

- name: Copy chezmoi config
  copy:
    src: chezmoi.toml
    dest: "{{ home }}/.config/chezmoi/chezmoi.toml"

- name: Decrypt chezmoi age key
  # requires pexpect python package to run
  expect:
    command: age -d -o "{{ home }}/.config/chezmoi/key.txt" "{{ home }}/.local/share/chezmoi/key.txt.age"
    responses:
      "Enter passphrase:": "{{ chezmoi_passphrase }}"
    creates: "{{ home }}/.config/chezmoi/key.txt"

- name: Set permissions on chezmoi age key
  file:
    path: "{{ home }}/.config/chezmoi/key.txt"
    mode: '0600'

# Used to `chezmoi apply` here, but it's better not to -- we already decrypt the key, which is the big one
# It prompts if files would be overwritten, which isn't worth it.

- name: Switch chezmoi remote to ssh
  command:
    cmd: git remote set-url origin git@github.com:almondheil/dotfiles.git
    chdir: "{{ home }}/.local/share/chezmoi"
