---
- name: Install Kitty terminal emulator
  become: true
  community.general.pacman:
    name: kitty
    state: present

- name: Install Seahorse password manager
  become: true
  community.general.pacman:
    name: seahorse
    state: present

- name: Install terminal text toys
  become: true
  community.general.pacman:
    name:
      - tree
      - cowsay
      - fortune-mod
      - figlet
      - lolcat
    state: present

- name: Install man pages
  become: true
  community.general.pacman:
    name: man-db
    state: present

- name: Install wayland clipboard
  become: true
  community.general.pacman:
    name: wl-clipboard
    state: present

- name: Install power profiles
  become: true
  community.general.pacman:
    name: power-profiles-daemon
    state: present

- name: Install flatseal
  flatpak:
    name: com.github.tchx84.Flatseal
    state: present

- name: Install discord
  flatpak:
    name: com.discordapp.Discord
    state: present

- name: Install ripgrep
  become: true
  community.general.pacman:
    name: ripgrep
    state: present

- name: Install preffered KDE editors
  become: true
  community.general.pacman:
    name:
      - gwenview
      - okular
      - ghostwriter
    state: present

- name: Install todo.txt from aur
  kewlfft.aur.aur:
    name: todotxt
    state: present
