---
- name: Install flatpak
  become: true
  community.general.pacman:
    name:
      - flatpak
    state: present

- name: Enable flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install firefox flatpak
  community.general.flatpak:
    name: org.mozilla.firefox
    state: present
