---
- name: Install flatpak
  become: true
  community.general.pacman:
    name: flatpak
    state: present

- name: Install Flatseal
  community.general.flatpak:
    name: com.github.tchx84.Flatseal
    state: present

