---
- name: Install zsh
  become: true
  community.general.pacman:
    name: zsh
    state: present

- name: Set user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh

# https://github.com/aturnr/ansible-role-ohmyzsh/blob/master/tasks/install.yml
- name: Install oh-my-zsh from git
  ansible.builtin.git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "{{ home }}/.oh-my-zsh"
    version: master
    update: false

# https://github.com/aturnr/ansible-role-ohmyzsh/blob/master/tasks/install.yml
- name: Set permissions on .oh-my-zsh directory
  ansible.builtin.file:
    path: "{{ home }}/.oh-my-zsh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0750'
