---
# https://github.com/kewlfft/ansible-aur
- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

# https://github.com/kewlfft/ansible-aur
- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0440
    validate: 'visudo -cf %s'

- name: Install rustup
  become: yes
  community.general.pacman:
    name: rustup
    state: present

- name: Set `aur_builder` rustup version to stable
  become: yes
  become_user: aur_builder
  command: rustup default stable

- name: Set running user rustup version to stable
  command: rustup default stable

- name: Install paru through the aur
  kewlfft.aur.aur:
    name: paru
    state: present
    use: makepkg
  become: yes
  become_user: aur_builder
