---
- name: Install aseprite build dependencies
  become: true
  community.general.pacman:
    name:
      - clang
      - cmark
      - compiler-rt
      - fmt
      - gn
      - tinyxml2
    state: present

- name: Build aseprite from aur
  kewlfft.aur.aur:
    name:
      - aseprite
      - aseprite-debug
    state: present
