---
- name: Disable switching applications
  gsetting:
    schema: org.gnome.desktop.wm.keybindings
    key: switch-applications
    value: '[]'

- name: Disable switching applications backward
  gsetting:
    schema: org.gnome.desktop.wm.keybindings
    key: switch-applications-backward
    value: '[]'

- name: Use Alt+Tab to switch windows
  gsetting:
    schema: org.gnome.desktop.wm.keybindings
    key: switch-windows
    value: "['<Alt>Tab']"

- name: Use Alt+Shift+Tab to switch windows backward
  gsetting:
    schema: org.gnome.desktop.wm.keybindings
    key: switch-windows-backward
    value: "['<Shift><Alt>Tab']"
