---
- name: Uninstall Epiphany browser
  become: true
  community.general.pacman:
    name: epiphany
    state: absent

- name: Uninstall Evince document viewer
  become: true
  community.general.pacman:
    name:
      - evince
      - sushi
    state: absent

- name: Install better gnome shell extensions from flathub
  community.general.flatpak:
    name: com.mattjakeman.ExtensionManager
    state: present
