---
# these are all in their own lil category, wheter I didn't feel like they fit anywhere
- name: Disable event sounds
  community.general.dconf:
    key: /org/gnome/desktop/sound/event-sounds
    value: 'false'

- name: Set favorite applications to none
  gsetting:
    schema: org.gnome.shell
    key: favorite-apps
    value: '[]'

- name: Set colorscheme to dark
  gsetting:
    schema: org.gnome.desktop.interface
    key: color-scheme
    value: "'prefer-dark'"

- name: Do not attach modal dialogs
  gsetting:
    schema: org.gnome.mutter
    key: attach-modal-dialogs
    value: 'false'

# these are all larger, so import them instead of just having them here
- name: Import apps tasks
  ansible.builtin.import_tasks: apps.yaml
- name: Import touchpad tasks
  ansible.builtin.import_tasks: touchpad.yaml
- name: Import shortcuts tasks
  ansible.builtin.import_tasks: shortcuts.yaml
- name: Import alt+tab tasks
  ansible.builtin.import_tasks: alt_tab.yaml
- name: Import workspace switching tasks
  ansible.builtin.import_tasks: workspace_switching.yaml
