---
# these are all in their own lil category, wheter I didn't feel like they fit anywhere
- name: Disable event sounds
  community.general.dconf:
    key: /org/gnome/desktop/sound/event-sounds
    value: 'false'

- name: Set favorite applications to none
  gsetting:
    schema: org.gnome.shell
    key: favorite-apps
    value: '[]'

- name: Swap keyboard caps and escape
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['caps:swapescape']"

- name: Set colorscheme to dark
  gsetting:
    schema: org.gnome.desktop.interface
    key: color-scheme
    value: "'prefer-dark'"

# these are all larger, so import them instead of just having them here
- import_tasks: apps.yml
- import_tasks: touchpad.yml
- import_tasks: shortcuts.yml
- import_tasks: alt_tab.yml
- import_tasks: workspace_switching.yml
