---
- name: Install fzf and its python package
  become: true
  community.general.pacman:
    name:
      - fzf
      - python-pyfzf
    state: present

- name: Install kitty (terminal emulator)
  become: true
  community.general.pacman:
    name: kitty
    state: present

- name: Install man pages
  become: true
  community.general.pacman:
    name: man-db
    state: present

- name: Install ripgrep
  become: true
  community.general.pacman:
    name: ripgrep
    state: present

- name: Install plocate
  become: true
  community.general.pacman:
    name: plocate
    state: present

- name: Install power profiles daemon
  become: true
  community.general.pacman:
    name: power-profiles-daemon
    state: present

- name: Install terminal toys
  become: true
  community.general.pacman:
    name:
      - cmatrix
      - cowsay
      - figlet
      - fortune-mod
      - lolcat
    state: present

- name: Install todo.txt from aur
  kewlfft.aur.aur:
    name: todotxt
    state: present

- name: Install tree
  become: true
  community.general.pacman:
    name: tree
    state: present

- name: Install trash-cli
  become: true
  community.general.pacman:
    name: trash-cli
    state: present

- name: Install wayland clipboard
  become: true
  community.general.pacman:
    name: wl-clipboard
    state: present

- name: Install latest ftag
  community.general.cargo:
    name: ftag
    state: latest

- name: Install latest gonote
  ansible.builtin.command:
    cmd: go install github.com/almondheil/gonote@latest
    creates: "{{ home }}/.go/bin/gonote"
  environment:
    GOPATH: "{{ home }}/.go"

- name: Install sg3 utils
  become: true
  community.general.pacman:
    name: sg3_utils
    state: present

- name: Install libdvdcss
  become: true
  community.general.pacman:
    name: libdvdcss
    state: present
