---
- name: Install go
  become: true
  community.general.pacman:
    name: go
    state: present

- name: Install personal gonote script
  ansible.builtin.command:
    cmd: go install github.com/almondheil/gonote@latest
    creates: "{{ home }}/.go/bin/gonote"
  environment:
    GOPATH: "{{ home }}/.go"
