- name: Install thunderbird
  become: true
  community.general.pacman:
    name: thunderbird
    state: present

- name: Install birdtray dependencies
  become: true
  community.general.pacman:
    name: qt5-tools
    state: present

- name: Install birdtray through AUR
  kewlfft.aur.aur:
    name:
      - birdtray
      - birdtray-debug
    state: present
