---
- name: Clone git projects to homedir (do not update if out-of-date)
  # noqa: latest
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ home }}/git/{{ item.name }}"
    update: false
    accept_newhostkey: true
  with_items: "{{ git_projects }}"
