- name: Install syncthing
  become: true
  community.general.pacman:
    name: syncthing
    state: installed

- name: Enable and start syncthing service for user
  ansible.builtin.systemd_service:
    name: syncthing
    state: started
    enabled: true
    scope: user

- name: Ensure syncthing dir is created
  ansible.builtin.file:
    path: "{{ sync_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "700"

- name: Create symlinks for syncthing items (once they sync)
  ansible.builtin.file:
    src: "{{ sync_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true # ignore if src does not exist
    follow: false # avoid ambiguity about following symlinks
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ sync_symlinks }}"
