---
- name: Install sg3 utils
  become: true
  community.general.pacman:
    name: sg3_utils
    state: present

- name: Install libdvdcss
  become: true
  community.general.pacman:
    name: libdvdcss 
    state: present

- name: Enable custom udev rule for superdrive
  become: true
  ansible.builtin.copy:
    src: 99-superdrive.rules
    dest: /etc/udev/rules.d/99-superdrive.rules
