- name: Delete `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    state: absent
    remove: true

- name: Remove `aur_builder` sudo rule
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent
