---
- name: Install all texlive tools (will take a long time)
  become: true
  community.general.pacman:
    name: texlive
    state: present

- name: Install biber
  become: true
  community.general.pacman:
    name: biber
    state: present
