- name: Symlink out of syncthing directory
  ansible.builtin.file:
    src: "{{ sync_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true # ignore if src does not exist (it won't)
    follow: false # avoid ambiguity about following symlinks
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ sync_symlinks }}"
