---
- name: Enable wanted system services
  become: true
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: true
  with_items: '{{ services.enabled.system | default([]) }}'

- name: Disable unwanted system services
  become: true
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: false
  with_items: '{{ services.disabled.system | default([]) }}'

- name: Enable wanted user services
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: true
    scope: user
  with_items: '{{ services.enabled.user | default([]) }}'

- name: Disable unwanted user services
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    enabled: false
    scope: user
  with_items: '{{ services.disabled.user | default([]) }}'
