# do not warn that ansible could change the version of python running
ansible_python_interpreter: auto_silent

# set user home
user: "almond"
home: "/home/{{ user }}"

# git projects to clone into ~/git
git_projects:
  - name: almondheil.github.io
    url: git@github.com:almondheil/almondheil.github.io.git
  - name: resume
    url: git@github.com:almondheil/resume.git
  - name: ftag
    url: git@github.com:almondheil/ftag.git
  - name: gonote
    url: git@github.com:almondheil/gonote.git

# syncthing directory and symlinks to be made out of it, into other locations
sync_dir: "{{ home }}/sync"
sync_symlinks:
  - src: "TODO.md"
    dest: "{{ home }}/TODO.md"
  - src: "dot_todo"
    dest: "{{ home }}/.todo"

# what directories should be removed from home, and what should be added?
home_subdir_remove:
  - Desktop
  - Documents
  - Downloads
  - Music
  - Pictures
  - Public
  - Templates
  - Videos
home_subdir_create:
  - download
  - sync
  - truenas-media
  - virtualbox

# things to install for use with the WM
# note: pacman tools get installed before aur, so dependencies can be listed
niri_tools:
  pacman:
    - brightnessctl             # screen brightness control
    - fuzzel                    # app launcher
    - gnome-keyring             # gnome's keyring for passwords
    - mako                      # notifications
    - org.freedesktop.secrets   # secrets portal
    - polkit-kde-agent          # plasma's polkit agent
    - swaybg                    # walpapers
    - swaylock                  # screen lock
    - xdg-desktop-portal-gnome  # niri screenscasting
    - xwayland-satellite        # run x11 apps in xwayland
  aur:
    - clipman                   # clipboard management
    - hyprpicker                # color picker
