---
- name: Enable multilib repo
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  notify:
    - Install vulkan for Intel integrated graphics
    - Install steam

- name: Drop steam-move-screenshots systemd units
  become: true
  ansible.builtin.template:
    src: "steam-move-screenshots.{{ item }}.j2"
    dest: "/usr/lib/systemd/system/steam-move-screenshots.{{ item }}"
    mode: '0644'
  with_items:
    - service
    - timer

- name: Drop steam-move-screenshots script
  become: true
  ansible.builtin.template:
    src: "steam-move-screenshots.sh.j2"
    dest: "/usr/bin/steam-move-screenshots.sh"
    mode: '0755'

- name: Start and enable steam-move-screenshots timer
  become: true
  ansible.builtin.systemd:
    name: steam-move-screenshots.timer
    state: started
    enabled: true
    daemon-reload: true
