---
- name: Disable event sounds
  community.general.dconf:
    key: /org/gnome/desktop/sound/event-sounds
    value: 'false'

- name: Uninstall Evince browser
  become: true
  community.general.pacman:
    name:
      - evince
      - sushi
    state: absent
