- name: Install terminal monospace font
  become: true
  community.general.pacman:
    name: ttf-inconsolata-nerd
    state: present

- name: Install Google noto fonts (incl. emoji and CJK)
  become: true
  community.general.pacman:
    name:
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
    state: present
